/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author RogerioSilva
 */
public class Jogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Jogo.class.getName());

    /**
     * Creates new form Jogo
     */
    
    
    //É O LOCAL ONDE CRIAMOS AS NOSSAS VARIAVEIS
    
    //JButton precisa da importacao da sua biblioteca
    //btnCampos e o nome da variavel - (Voce que escolhe)
    //Matriz com - 10 linhas e 10 colunas
    JButton [][] btnCampos = new JButton [10][10];
    
    //MATRIZ PARA GUARDAR AS BOMBAS - true p/ bomba, false p/numero
    boolean [][] bombas = new boolean [10][10];
    
    //MATRIZ PARA GUARDAR OS CAMPOS QUE FORAM ABERTOS
    boolean [][] abertos = new boolean [10][10];
    
    //variavel para guardar as bombas / quantidade de bombas
    int quantidadeBombas = 15;
    boolean jogoEncerrado = false;
    
   
    
    
    
    
    
    //CONSTRUTOR DA CLASSE - SEM ELE A TELA NAO FUNCIONA
    public Jogo() {
        initComponents();
        CriarTabuleiro();
    }
    
    //  CRIAR AS NOSSAS FUNCOES/METODOS
    public void CriarTabuleiro(){
       //definir que o painel sera dividido em 10 linhas e 10 colunas
       //com altura 2px e largura 2px
       painelcampo.setLayout(new GridLayout(10,10,100,100)); 
        
       //laco de repeticao
        for(int coluna=0;coluna<=9;coluna++){
            for(int linha=0;linha<=9;linha++){
                //variavel botao para guadar os dados provisorios
                JButton botao = new JButton();              
                botao.setFont(new Font("Palatino LinoType",Font.BOLD,48));//FONTE
                botao.setBackground(new Color(96,96,96));//COR DE FUNDO
                botao.setForeground(Color.WHITE);//COR DE TEXTO
                
                //REMOVER MARCAS DO BOTAO QUE VEM POR PADRAO
                botao.setFocusPainted(false);
                botao.setEnabled(false);
                
                //adc o botao dentro da matriz
                btnCampos[linha][coluna]=botao;
                //adc ele dentro do painel
                painelcampo.add(botao);
                
                
           }//fim do 2° for
       } //fim do 1° for
        
    }//fim do metodo CriarTabuleiro
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        tfTempo = new javax.swing.JTextField();
        painelcampo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setBackground(new java.awt.Color(0, 0, 0));
        Titulo.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 204, 204));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Campo Minado");

        btnIniciar.setBackground(new java.awt.Color(0, 204, 204));
        btnIniciar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("INICIAR");
        btnIniciar.setToolTipText("");
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);

        tfTempo.setEditable(false);
        tfTempo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfTempo.setText("00:00");
        tfTempo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        painelcampo.setBackground(new java.awt.Color(153, 153, 153));
        painelcampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        painelcampo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout painelcampoLayout = new javax.swing.GroupLayout(painelcampo);
        painelcampo.setLayout(painelcampoLayout);
        painelcampoLayout.setHorizontalGroup(
            painelcampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
        painelcampoLayout.setVerticalGroup(
            painelcampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelcampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIniciar)
                            .addComponent(tfTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciar))
                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(painelcampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Jogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JPanel painelcampo;
    private javax.swing.JTextField tfTempo;
    // End of variables declaration//GEN-END:variables
}
